export const REPOSACTION = "REPOS_ACTION";
export const REPOSACTIONSUCCESS = "REPOS_ACTION_SUCCESS";
export const SINGLREPOSACTION = "SINGL_REPOS_ACTION";
export const SINGLREPOSACTIONSUCCESS = "SINGL_REPOS_ACTION_SUCCESS";
