export const USERS_ACTION_TYPES = {
  USERS_GET_REQUEST: "USERS: GET_REQUEST",
  USERS_GET_REQUEST_SUCCESS: "USERS: GET_REQUEST_SUCCESS",
  USERS_GET_SINGLE_REQUEST: "USERS: GET_SINGLE_REQUEST",
  USERS_GET_SINGLE_REQUEST_SUCCESS: "USERS: GET_SINGLE_REQUEST_SUCCESS"
};
